=== education-service/hfut-face-plate/hfut-lpr/src/main/resources/dtd/syntax.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT char EMPTY >
<!ATTLIST char content NMTOKEN #REQUIRED >

<!ELEMENT structure ( type+ ) >

<!ELEMENT type ( char+ ) >
<!ATTLIST type name NMTOKEN #REQUIRED >

=== education-service/hfut-face-plate/hfut-lpr/src/main/resources/syntax/syntax.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structure SYSTEM "src/main/resources/dtd/syntax.dtd">

<structure>
    <type name="germany">
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="0123456789" />
        <char content="0123456789" />
        <char content="0123456789" />
    </type>

    <type name="slovensko_nova">
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="abcdefghijklmno0pqrstuvwxyz" />
    </type>

    <type name="ceskoslovenska_novsia">
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="o0123456789" />
    </type>

    <type name="ceskoslovenska_starsia">
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="abcdefghijklmno0pqrstuvwxyz" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="o0123456789" />
    </type>

    <type name="ceska_nova">
        <char content="o0123456789" />
        <char content="cbkhltmepasujz" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="o0123456789" />
        <char content="o0123456789" />
    </type>
</structure>
